services:
  postgres:
    image: "postgres:16"
    container_name: "postgres"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "user=postgres password=postgres dbname=postgres"]
      interval: 5s
      timeout: 90s
      retries: 300
    ports:
      - "5432:5432"
    volumes:
      - postgres_data1:/var/lib/postgresql/data

  fastapi_app:
    container_name: "fastapi"
    build:
      dockerfile: ./Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"

  recommender:
    container_name: "recommender"
    volumes:
      - model_data:/app/model
    build:
      context: recommendations
      dockerfile: Dockerfile
    ports:
      - "5100:5100"



volumes:
  postgres_data1:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./dbdata

  model_data: