services:
  postgres:
    image: "postgres:16"
    container_name: "postgres"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "user=postgres password=postgres dbname=postgres"]
      interval: 5s
      timeout: 90s
      retries: 300
    ports:
      - "5432:5432"
    volumes:
      - postgres_data1:/var/lib/postgresql/data

  frontend:
    container_name: "frontend"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    depends_on:
      fastapi_app:
        condition: service_healthy

  fastapi_app:
    container_name: "fastapi"
    build:
      dockerfile: ./Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "8000:8000"

  recomender:
    container_name: "recomender"
    volumes:
      - model_data:/app/model
    build:
      context: recomendations
      dockerfile: Dockerfile
    ports:
      - "5100:5100"

volumes:
  model_data:
  postgres_data1:

# volumes:
  # - ./postgres_data:/var/lib/postgresql/data
  # - ./model_data:/app/model