"""empty message

Revision ID: 1d8c82ac182d
Revises: ea46efd5310c
Create Date: 2025-03-26 21:39:02.695835

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1d8c82ac182d'
down_revision: Union[str, None] = 'ea46efd5310c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'title',
                    existing_type=sa.VARCHAR(length=64),
                    type_=sa.String(length=128),
                    existing_nullable=False)
    op.alter_column('products', 'seller',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'seller',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('products', 'title',
                    existing_type=sa.String(length=128),
                    type_=sa.VARCHAR(length=64),
                    existing_nullable=False)
    # ### end Alembic commands ###
