"""empty message

Revision ID: 5368960667aa
Revises: 390f978583b4
Create Date: 2025-03-04 14:13:18.702059

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5368960667aa'
down_revision: Union[str, None] = '390f978583b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('carts', 'products',
                    existing_type=postgresql.JSON(astext_type=sa.Text()),
                    nullable=True)
    op.alter_column('products', 'tags',
                    existing_type=postgresql.JSON(astext_type=sa.Text()),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'tags',
                    existing_type=postgresql.JSON(astext_type=sa.Text()),
                    nullable=False)
    op.alter_column('carts', 'products',
                    existing_type=postgresql.JSON(astext_type=sa.Text()),
                    nullable=False)
    # ### end Alembic commands ###
