"""empty message

Revision ID: ea819cdd09ae
Revises: 1d8c82ac182d
Create Date: 2025-04-11 19:50:00.564852

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea819cdd09ae'
down_revision: Union[str, None] = '1d8c82ac182d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('carts_id_fkey', 'carts', type_='foreignkey')
    op.create_foreign_key(None, 'carts', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('phone', sa.String(length=15), nullable=True))
    op.alter_column('users', 'email',
                    existing_type=sa.VARCHAR(length=30),
                    nullable=True)
    op.alter_column('users', 'name',
                    existing_type=sa.VARCHAR(length=30),
                    nullable=True)
    op.drop_column('users', 'preferences')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users',
                  sa.Column('preferences', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column('users', 'name',
                    existing_type=sa.VARCHAR(length=30),
                    nullable=False)
    op.alter_column('users', 'email',
                    existing_type=sa.VARCHAR(length=30),
                    nullable=False)
    op.drop_column('users', 'phone')
    op.drop_constraint(None, 'carts', type_='foreignkey')
    op.create_foreign_key('carts_id_fkey', 'carts', 'users', ['id'], ['id'])
    op.drop_column('carts', 'user_id')
    # ### end Alembic commands ###
