"""empty message

Revision ID: ed46cddded8c
Revises: ea819cdd09ae
Create Date: 2025-04-11 19:50:54.546065

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ed46cddded8c'
down_revision: Union[str, None] = 'ea819cdd09ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('carts', 'user_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('users', 'phone',
                    existing_type=sa.VARCHAR(length=15),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone',
                    existing_type=sa.VARCHAR(length=15),
                    nullable=True)
    op.alter_column('carts', 'user_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###
